language: generic

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

git:
  depth: 10

branches:
  only:
    - master
